//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public System.Guid Id { get; set; }
        public System.Guid IdUsuario { get; set; }
        public Nullable<System.DateTime> HoraEntrada { get; set; }
        public Nullable<System.DateTime> SaidaAlmoco { get; set; }
        public Nullable<System.DateTime> VoltaAlmoco { get; set; }
        public Nullable<System.DateTime> HoraSaida { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<bool> FlAbonado { get; set; }
    }
}
