//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RioEntities : DbContext
    {
        public RioEntities()
            : base("name=RioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Grupo> Grupo { get; set; }
        public DbSet<Projeto> Projeto { get; set; }
        public DbSet<StausProjeto> StausProjeto { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Alocacao> Alocacao { get; set; }
        public DbSet<Livro> Livro { get; set; }
    }
}
